language: generic
env:
  global:
  - USER="sjimenez77"
  - EMAIL="sjimenez77@gmail.com"
  - REPO_SOURCE="test-travis-wiki"
  - REPO_DEST="test-travis-wiki.wiki"
  - GH_REPO_SOURCE="github.com/${USER}/${REPO_SOURCE}.git"
  - GH_REPO_DEST="github.com/${USER}/${REPO_DEST}.git"
  - secure: judj0sYaL0Yklb9we02kfkMkno+e7SLCRDw3Qsys78vfv/Cw2ESpQKA9UtrLA7SEKwG5iQ5BIS2esA3eIHc3UjtooM2CR3L1TnmO2v3aIFuxLQ8ids3JivED2s9o/P/O17kHqdOlADH0e1T8shq9VcGrdCnp+Z8tEeSFSHttp0bNVWFEoC2Wb9Bpxid9fFQ4r6EAzHH96n/U4NtAM318NpiludZOXxSPC7eplqn5IpTXVGApQy4G47ZQYmdI9DEpEWjZN08P/R2cLg9+kGOYXhPzQuzjCaGnN4O21WiPtrXUCTb+Pamw6DpF5XNQwzrFtb76HiuXFeAMdtqLE5/fw3Ge7Bwh7yAZKH9s0mvYF4TpUUvZGHzFqzQV9iZFTuOep+24oRQGF3WaMijfeXNDrXTrYqXChV1NVvW33gQdm8iP2lJuY5Y5AZ/GWJx8/X0d2mKyiqNHTVmerpBlRPMHLWHZvUliMotDsusXoqsswqfo8GsN/XbwZYkOCOH8yua9IdLRBipWDIiJvmmEcUsAbc6NfcqLCgx2xLju1yihLdZifVsRPyj7cLWF1fBzfOPLnvO7B2ldw5i9CIG0GQUybt2MhXG37ZCEnULoOi/uH581pKhh+E3G/+ROl5RfT3HYrCk5h4XZ98/YIOFYceQB515nbZKS4+91y447EJdkgQ4=
script:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- git clone https://${GH_REPO_SOURCE}
- git clone https://${GH_REPO_DEST}
- yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
- cd ${REPO_DEST}
- pwd
- git remote
- git config user.email ${EMAIL}
- git config user.name ${USER}
- git add .
- git status
- git commit -m "${MESSAGE}"
- git remote add origin-wiki "https://${GITHUB_TOKEN}@${GH_REPO_DEST}"
- git push origin-wiki master
