language: generic
env:
  global:
  - USER="sjimenez77"
  - EMAIL="sjimenez77@gmail.com"
  - REPO_SOURCE="test-travis-wiki"
  - REPO_DEST="test-travis-wiki.wiki"
  - GH_REPO_SOURCE="github.com/${USER}/${REPO_SOURCE}.git"
  - GH_REPO_DEST="github.com/${USER}/${REPO_DEST}.git"
  - secure: Hk/YV6+qLCeAX/7PV4VYRqjms1c+msfA45OSuMjGFM5k0I0t134WgCMVAZdvSPAeLVKxwYM1wmX5IHaeamf9GEilJVM4s/8VVb/FtX8iopqmg+I74O25C005e526cVqe/yYY5cuPoOLmRtHSM/9rWgWdQLzdEv+a8BLrixLgmvu2l8mLaGj4X9KWZkFhabL3Sg73BpWMSVfOsu4Ypsmexvp2C0cjL+zBh5kCsUDQ6tUu+bDTegiNoMsaqYoH2paK3L3eK7vGuPGj/+TV2V4KaesuqZRjSv092XJaPIPscktADChXObfJcON9Dn20g55lfRij5iRZDC1hbK5K5myTDkchVoWm2mNhIirnWf71jxkkNjvMHj20lbvyex7KLlMYS7FP8rQbTpwQzvv3Cw/U2zvIOmevL5pnEqzk/BR337mG6wz15M8uayOuSjg/tRzp9zELOjXFWud3iHk+cDse2hq4HFCEpkt85OVgkJ/5x1gAs54Jff54mWx3lJAmajg1uNuFZnCKB9hAcKdru30SR7Ko7hjZv/ve33tjdOoUP5U08ZheVDjJ4jTnpBIjtTvqcfzBxtzeRTpxd7ka64tD4aEcK/RRVMF1rDDV67SIcZx9h5xamadhLnWjKjHYS6mkt3/HJ6RzFa2EdA9NZruS/CqhIFNas5TVFmyvx1GGVPg=
script:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- git clone https://${GH_REPO_SOURCE}
- git clone https://${GH_REPO_DEST}
- yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
- cd ${REPO_DEST}
- git remote
- git config user.email ${EMAIL}
- git config user.name ${USER}
- git add .
- git commit -m "${MESSAGE}"
- git remote add origin-wiki "https://${GITHUB_TOKEN}@${GH_REPO_DEST}"
- git push origin-wiki master > /dev/null 2>&1
