language: generic
env:
  global:
  - USER="sjimenez77"
  - EMAIL="sjimenez77@gmail.com"
  - REPO_SOURCE="test-travis-wiki"
  - REPO_DEST="test-travis-wiki.wiki"
  - GH_REPO_SOURCE="github.com/${USER}/${REPO_SOURCE}.git"
  - GH_REPO_DEST="github.com/${USER}/${REPO_DEST}.git"
  - secure: uGWfFsLObtS+lCkTpWD4M2/ev0nulAU3hqUJWKLjQU6IO4S8/sYJ+XjoqWBq9b0nAnOvnqvj/JOJgvFoTzV0jrxiEVej5NnNhtmJcP7CDxShyzpzbDZJ1Gz5eKpg4guQ0OJRUaTEsC8yhORTP+GfuVI8izLVOsFHIsCAxOKDAnlCe4GrexFN+743Nks+bd5FAkKho6qHoAkPZlJ8+aBnKYVZvOi+n69Tc0RtqsdTJQhatAlV4f+S5PaYx7nhNd/f09RBLuoLj/W85JWFHxrgJob2Hq7TWtl+nAUyJLV+9ItPuV5A+GqE57Mqu2VAibrYcXUotZMSs4pxK14yXCB1IIC0jsfG2Zt91SfEEuhEgdgze9AUlBLlbFhAP6pHzDVyXU4r3fjamhUDiWqhOrOY3XvtLetODzG2BQ2ASAM8d6SD16Re59leRBkXoQx892twtekhme5KEL/xoypn37IpLkl7mWGSytEOetU9wQAvAFvxUbNGg+sUZTzRq47F6A0hI1i0AflAHYyhQ//izNFetoXu90VFF9S9nhGaJIEBaM5lG0EE/t4XruYV4OSCFFBAg8on4jvuKJ2AsGIQ455FgxoIEmSZAb8jHn38Sbwc3nI3Ba7QUblZN4kg+NG92+5vF8AuQ4cKaNxwE+LMt5HC8TKM0oHfHLaQnQ6hrxNGVQQ=
script:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- git clone https://${GH_REPO_SOURCE}
- git clone https://${GH_REPO_DEST}
- yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
- cd ${REPO_DEST}
- pwd
- git remote
- git config user.email ${EMAIL}
- git config user.name ${USER}
- git add .
- git status
- git commit -m "${MESSAGE}"
- git remote add origin-wiki "https://${GITHUB_TOKEN}@${GH_REPO_DEST}"
- git push origin-wiki master
