language: generic
env:
  global:
  - USER="sjimenez77"
  - EMAIL="sjimenez77@gmail.com"
  - REPO_SOURCE="test-travis-wiki"
  - REPO_DEST="test-travis-wiki.wiki"
  - GH_REPO_SOURCE="github.com/${USER}/${REPO_SOURCE}.git"
  - GH_REPO_DEST="github.com/${USER}/${REPO_DEST}.git"
script:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone https://${GH_REPO_SOURCE}
  - git clone https://${GH_REPO_DEST}
  - yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
  - cd ${REPO_DEST}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add .
  - git commit -m "${MESSAGE}"
  - git push "https://${TRAVIS_SECURE_TOKEN_NAME}@${GH_REPO}" master > /dev/null 2>&1